version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: networkx
    versions:
    - "2.5"
  - dependency-name: jinja2
    versions:
    - 2.10.1
  - dependency-name: numpy
    versions:
    - 1.20.1
